export const movieImages = [
  { name: "Action", 
    imgUrl: "https://wallpapercave.com/w/wp12110395.jpg",
  },
  {
    name: "Adventure",
    imgUrl: "https://wallpapercave.com/wp/wp5758792.jpg",
  },
  {
    name: "Animation",
    imgUrl: "https://wallpapercave.com/w/wp9011587.jpg",
  },
  { name: "Comedy", 
    imgUrl: "https://wallpapercave.com/w/wp11029112.jpg" 
  },
  {
    name: "Mystery",
    imgUrl: "https://wallpapercave.com/dwp1x/wp7042382.jpg",
  },
  { name: "Sport", 
    imgUrl: "https://wallpapercave.com/wp/wp9055386.jpg",
  },
  { name: "Horror", 
    imgUrl: "https://wallpapercave.com/w/wp4705452.jpg",
  },
  {
    name: "Documentary",
    imgUrl: "https://wallpapercave.com/dwp1x/wp1967574.jpg",
  },
  { name: "War", 
    imgUrl: "https://wallpapercave.com/wp/wp5010585.jpg",
  },
  { name: "Drama", 
    imgUrl: "https://wallpapercave.com/dwp1x/wp2014257.jpg",
  },
  { name: "Family", 
    imgUrl: "https://wallpapercave.com/dwp1x/wp10808227.jpg",
  },
  {
    name: "Fantasy",
    imgUrl: "https://wallpapercave.com/dwp1x/wp6986688.jpg",
  },
  {
    name: "History",
    imgUrl: "https://wallpapercave.com/dwp1x/wp11710569.jpg",
  },
  { name: "Crime",
    imgUrl: "https://wallpapercave.com/dwp1x/wp3008006.jpg",
  },
  { name: "Music", 
    imgUrl: "https://wallpapercave.com/wp/wp3982559.jpg",
  },
  {
    name: "Biography",
    imgUrl: "https://wallpapercave.com/dwp1x/wp2438088.jpg",
  },
  {
    name: "Western",
    imgUrl: "https://wallpapercave.com/dwp1x/wp7128299.jpg",
  },
  { name: "Science Fiction", 
    imgUrl: "https://wallpapercave.com/wp/wp6999376.jpg",
  },
  { name: "Thriller", 
    imgUrl: "https://wallpapercave.com/dwp1x/wp8313457.jpg",
  },
  { name: "TV Movie", 
    imgUrl: "https://wallpapercave.com/dwp1x/wp12009646.jpg",
  },
  { name: "Romance", 
    imgUrl: "https://wallpapercave.com/wp/wp8953295.jpg",
  },
];

export const tvImages = [
  { name: "Action & Adventure", 
    imgUrl: "https://wallpapercave.com/dwp1x/Kcaqj7R.jpg",
  },
  {
    name: "Animation",
    imgUrl: "https://wallpapercave.com/dwp1x/wp10797683.jpg",
  },
  { name: "Comedy", 
    imgUrl: "https://wallpapercave.com/dwp1x/wp11839482.jpg" 
  },
  {
    name: "Mystery",
    imgUrl: "https://wallpapercave.com/dwp1x/wp2360853.jpg",
  },
  {
    name: "Documentary",
    imgUrl: "https://wallpapercave.com/dwp1x/wp11590840.jpg",
  },
  { name: "Drama", 
    imgUrl: "https://wallpapercave.com/dwp1x/wp4798900.jpg",
  },
  { name: "Family", 
    imgUrl: "https://wallpapercave.com/dwp1x/wp4208250.jpg",
  },
  {
    name: "Kids",
    imgUrl: "https://wallpapercave.com/dwp1x/wp4973656.jpg",
  },
  { name: "Crime",
    imgUrl: "https://wallpapercave.com/dwp1x/wp2156334.jpg",
  },
  {
    name: "Western",
    imgUrl: "https://wallpapercave.com/dwp1x/wp10221300.jpg",
  },
  { name: "Sci-Fi & Fantasy", 
    imgUrl: "https://wallpapercave.com/dwp1x/wp4208294.jpg",
  },
  { name: "Reality", 
    imgUrl: "https://wallpapercave.com/dwp1x/wp4208244.jpg",
  },
  { name: "Soap", 
    imgUrl: "https://wallpapercave.com/dwp1x/wp9197627.jpg",
  },
  { name: "War & Politics", 
    imgUrl: "https://wallpapercave.com/dwp1x/wp12084736.jpg",
  },
  { name: "Talk", 
    imgUrl: "https://wallpapercave.com/dwp1x/wp2363789.jpg",
  },
  { name: "News", 
    imgUrl: "https://wallpapercave.com/dwp1x/wp12182063.jpg",
  },
];
